/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/tasks` | `/tasks`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/lists` | `/lists`; params?: Router.UnknownInputParams; } | { pathname: `/settings/settings`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } } | { pathname: `${'/(tabs)'}/tasks/[taskId]` | `/tasks/[taskId]`, params: Router.UnknownInputParams & { taskId: string | number; } } | { pathname: `${'/(tabs)'}/lists/[listId]` | `/lists/[listId]`, params: Router.UnknownInputParams & { listId: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/home` | `/home`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/tasks` | `/tasks`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/lists` | `/lists`; params?: Router.UnknownOutputParams; } | { pathname: `/settings/settings`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } } | { pathname: `${'/(tabs)'}/tasks/[taskId]` | `/tasks/[taskId]`, params: Router.UnknownOutputParams & { taskId: string; } } | { pathname: `${'/(tabs)'}/lists/[listId]` | `/lists/[listId]`, params: Router.UnknownOutputParams & { listId: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/home${`?${string}` | `#${string}` | ''}` | `/home${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/tasks${`?${string}` | `#${string}` | ''}` | `/tasks${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/lists${`?${string}` | `#${string}` | ''}` | `/lists${`?${string}` | `#${string}` | ''}` | `/settings/settings${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/tasks` | `/tasks`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/lists` | `/lists`; params?: Router.UnknownInputParams; } | { pathname: `/settings/settings`; params?: Router.UnknownInputParams; } | `/+not-found${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/tasks/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/tasks/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/lists/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/lists/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } } | { pathname: `${'/(tabs)'}/tasks/[taskId]` | `/tasks/[taskId]`, params: Router.UnknownInputParams & { taskId: string | number; } } | { pathname: `${'/(tabs)'}/lists/[listId]` | `/lists/[listId]`, params: Router.UnknownInputParams & { listId: string | number; } };
    }
  }
}
